### ISSUE TITLE
Formulario de búsqueda de heroes

### ISSUE THREAD

**Issue by ardiadrianadri** [ardiadrianadri/super-heroe-react#6]
Como **usuario de la wiki** necesito tener en la home un componente formulario que me permita poder introducir el nombre de un personaje de marvel y realizar una búsqueda

### Notas:
El formulario se compondrá de un único input + un label + un botón de búsqueda. El componente formulario se dará como acabado cuando emita un evento cada vez que se pulsa el botón de búsqueda y propague al componente padre el contenido del input.

**Comment by uRuiz** [comment]
Component created and the branch was merged into dev
